config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # 管理者側
  devise_for :managers, controllers: {
    sessions: 'managers/sessions',
    passwords: 'managers/passwords',
    # TODO: 後で登録できないようにする
    registrations: 'managers/registrations'
  }

  devise_scope :manager do
    post 'login_as_guest_manager', to: 'managers/sessions#login_as_guest_manager'
  end
  namespace :managers do
    resources :cookedstates, except: [:show] do
      member do
        get 'restore'
      end
    end

    resources :cuisines
    resources :foodcategories, except: [:show]
    resources :foodstuffs, except: [:index, :show] do
      member do
        put :sort
      end
      collection do
        get 'search_foodcategory'
        get 'search_rawmaterial'
        get 'search_unit'
      end
    end

    resources :ingredients, except: [:show] do
      member do
        get 'restore'
      end
    end

    resources :procedures, except: [:index] do
      member do
        put :sort
      end
    end

    resources :rawmaterials do
      member do
        get 'restore'
      end
    end
    get 'dashboard', to: 'tops#dashboard'
    put 'toggle_editable', to: 'tops#toggle_editable', as: 'toggle_editable'
  end

  # ユーザー側
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'login_as_guest_user', to: 'users/sessions#login_as_guest_user'
  end
  resources :cookinghistorys, only: [:index, :destroy]
  resources :cuisines, only: [:show] do
    delete :remove_favorite
    delete :remove_menu
    delete :remove_from_todays_menus, action: :remove_from_todays_menus, controller: 'cookinghistorys'
    post :add_favorite
    post :add_menu
    post :add_to_todays_menu, action: :add_to_todays_menu, controller: 'cookinghistorys'
    collection do
      get :search
    end
  end
  resources :contacts, only: [:show, :new, :create]
  resources :favorites, only: [:index, :destroy]
  post '/add_todaysmenu/:cuisine_id', to: 'favorites#add_todaysmenu_from_favorite', as: 'add_todaysmenu_from_favorite'
  delete '/remove_todaysmenu/:cuisine_id', to: 'favorites#remove_todaysmenu_from_favorite', as: 'remove_todaysmenu_from_favorite'
  resources :keywords, only: [:index]
  resources :managecuisines do
    patch :toggle_status
  end
  resources :manageownfoodstuffs
  resources :manageownprocedures
  resources :userrawmaterials, only: [:index, :new, :create]
  resources :stocks, only: [:index, :new, :create, :destroy] do
    collection do
      get 'auto_today_create'
      get 'search_rawmaterial'
      get 'search_unit_and_expiry_period'
    end
  end
  resources :todaysmenus, only: [:index, :update, :destroy] do
    collection do
      post 'cooked_done'
    end
  end

  # TODO: 原材料から探せるようにする
  # get 'rawmaterials/search'
  get 'search/foodcategory_search', to: 'search#foodcategory_search'
  get 'search/rawmaterial_search', to: 'search#rawmaterial_search'
  get 'search/unit_search', to: 'search#unit_search'
  get '/about', to: 'tops#about'
  # get 'tops/index'
  get 'user/profile', to: 'users#show'
  put 'update_profile', to: 'users#update'

  root to: 'tops#index'

  # letter_opener_web
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/manageownfoodstuffs_controller.rb
# frozen_string_literal: true

class ManageownfoodstuffsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_foodstuff, only: %i[edit update destroy]
  before_action :set_and_check_cuisine, only: %i[new create edit update destroy]

  def new
    extract_instances(@cuisine)
    @foodstuff = Foodstuff.new
  end

  def edit
    extract_instances(@cuisine)
  end

  def create
    @foodstuff = Foodstuff.new(foodstuff_params)
    if @foodstuff.save
      redirect_to new_manageownfoodstuff_path(cuisine_id: @foodstuff.cuisine_id), flash: { notice: "#{@foodstuff.rawmaterial.name} が追加されました" }
    else
      @cuisine = Cuisine.find(@foodstuff.cuisine_id)
      extract_instances(@cuisine)
      params[:cuisine_id] = @foodstuff.cuisine_id
      render 'new'
    end
  end

  def update
    if @foodstuff.update(foodstuff_params)
      redirect_to new_manageownfoodstuff_path(cuisine_id: @foodstuff.cuisine_id), flash: { notice: '変更されました' }
    else
      @cuisine = Cuisine.find(@foodstuff.cuisine_id)
      extract_instances(@cuisine)
      params[:cuisine_id] = @foodstuff.cuisine_id
      render 'edit'
    end
  end

  def destroy
    @foodstuff.destroy
    redirect_to new_manageownfoodstuff_path(cuisine_id: @foodstuff.cuisine_id), flash: { notice: "#{@foodstuff.rawmaterial.name} が削除されました" }
  end

  private

  def extract_instances(cuisine)
    @foodstuffs = cuisine.foodstuffs.includes(rawmaterial: :unit)
    @procedures = cuisine.procedures
    @rawmaterials = Rawmaterial.all
  end

  def set_and_check_cuisine
    case params[:action].to_sym
    when :new
      @cuisine = Cuisine.find(params[:cuisine_id])
    when :create
      @cuisine = Cuisine.find(params[:foodstuff][:cuisine_id])
    when :edit, :update, :destroy
      @cuisine = Cuisine.find(@foodstuff.cuisine_id)
    end
    check_owner(@cuisine.user, current_user)
  end

  def set_foodstuff
    @foodstuff = Foodstuff.find(params[:id])
  end

  def foodstuff_params
    params.require(:foodstuff).permit(:id, :quantity, :cuisine_id, :rawmaterial_id, :row_order_position)
  end
end

app/helpers/manageownfoodstuffs_helper.rb
# frozen_string_literal: true

module ManageownfoodstuffsHelper
end

app/views/manageownfoodstuffs/_foodstuff.html.erb
<tr id="foodstuff_<%= foodstuff.id %>">
  <td class="align-middle" style="width: 40%"><%= foodstuff.rawmaterial.name %></td>
  <td class="align-middle" style="width: 30%"><%= foodstuff.quantity %><%= foodstuff.rawmaterial.unit.name unless foodstuff.quantity.start_with?('適量', '少々', 'お好みで') %></td>

  <td class="align-middle" style="width: 30%">
    <%= link_to edit_manageownfoodstuff_path(foodstuff.id),
                class: 'btn btn-default btn-outline-secondary',
                local: true do %>
      <i class="fas fa-pen"></i>
    <% end %>
    <%= link_to manageownfoodstuff_path(id: foodstuff.id, cuisine_id: @cuisine.id),
                class: 'btn btn-default btn-outline-secondary mt-1 mt-md-0',
                method: :delete do %>
      <i class="far fa-trash-alt"></i>
    <% end %>
  </td>
</tr>

app/views/manageownfoodstuffs/_form.html.erb
<div class="form-group col-10 offset-1">
  <label for="rawmaterial_id" class="col-12">食材</label>
  <%= form.collection_select :rawmaterial_id, @rawmaterials, :id, :name, { include_blank: '選択して下さい' }, { autofocus: true, class: 'col-12 offset-0 select_foodstuff form-control' } %>
</div>
<div class="form-group col-10 offset-1">
  <%= form.label :quantity, class: 'col-12' %>
  <div class="input-group">
    <%= form.text_field :quantity, id: 'foodstuff_quantity', class: 'form-control' %>
    <div class="input-group-prepend">
      <div class="input-group-text" id="rawmaterial_measure_unit">
        <% if @rawmaterial.present? %>
        <%= @rawmaterial.unit.name %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="ambiguous-value d-flex justify-content-around mt-2 mb-4">
    <div>
      <input type="radio" name="rough_quantity" id="proper" value="適量" />適量
    </div>
    <div>
      <input type="radio" name="rough_quantity" id="little" value="少々" />少々
    </div>
    <div>
      <input type="radio" name="rough_quantity" id="asyoulike" value="お好みで" />お好みで
    </div>
  </div>
  <%= form.hidden_field :cuisine_id, id: :foodstuff_cuisine_id, value: @cuisine.id %>
</div>

app/views/manageownfoodstuffs/_procedure.html.erb
<tr id="procedure_<%= procedure.id %>">
  <td class="idx-procedure align-middle"><%= procedure_counter + 1 %></td>
  <td class="cooking-details">
    <div class="text-break"><%= procedure.cooking_detail %></div>
    <div class="btns float-right">
      <%= link_to edit_manageownprocedure_path(procedure.id),
                  class: 'btn btn-default btn-outline-secondary',
                  local: true do %>
        <i class="fas fa-pen"></i>
      <% end %>
      <%= link_to manageownprocedure_path(id: procedure.id),
                  class: 'btn btn-default btn-outline-secondary mt-1 mt-md-0',
                  method: :delete do %>
        <i class="far fa-trash-alt"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/manageownfoodstuffs/edit.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12 col-md-8 offset-md-2 text-center mt-3">
        <div class="page-title m-0 d-inline">食材の変更</div>
        <div>(<%= @cuisine.name %>)</div>
      </div>
    </div>
  </div>
</div>

<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <%= form_with(model: @foodstuff, url: manageownfoodstuff_path, method: :patch, local: true) do |form| %>
            <%= render 'layouts/flash_message' %>
            <%= render 'shared/error_messages', { resource: @foodstuff } if @foodstuff.errors.any? %>
            <%= render 'form', { form: form, cuisine: @cuisine } %>
            <div class="col-10 offset-1">
            <%= form.submit '更新する', class: 'btn btn-success btn-block' %>
            </div>
            <div class="col-10 offset-1 mt-2">
              <%= link_to '手順登録へ', new_manageownprocedure_path(cuisine_id: @cuisine.id), class: 'btn btn-outline-secondary btn-block' %>
            </div>
        <% end %>
        <!-- foodstuffs and procedure list -->
        <div class="mt-2">
          <ul class="nav nav-tabs nav-fill" role="tablist" id="fp-tab">
            <li class="nav-item" role="presentation">
              <a class="nav-link active" role="tab" data-toggle="tab" href="#tab1" id="tab-foodstuff">食材</a>
            </li>
            <li class="nav-item" role="presentation">
              <a class="nav-link" role="tab" data-toggle="tab" href="#tab2" id="tab-procedure">手順</a>
            </li>
          </ul>
          <div class="tab-content">
            <div class="tab-pane active" role="tabpanel" id="tab1">
            <% if @foodstuffs.present? %>
              <table id="table-sortable-procedure" class="table table-bordered table-hover mt-3">
                <tbody>
                  <%= render partial: 'foodstuff', collection: @foodstuffs, as: 'foodstuff' %>
                </tbody>
              </table>
            <% else %>
              <div class="text-center mt-3">
                <p>まだ登録がありません</p>
              </div>
            <% end %>
            </div>
            <div class="tab-pane" role="tabpanel" id="tab2">
              <div class="procedure-list">
                <% @procedures.each_with_index do |pd, idx| %>
                  <div class="row mt-3">
                    <div class="col-2 offset-1 d-flex justify-content-end align-items-center">
                      <div class="foodstuff-number">
                          <p><%= idx + 1 %>.</p>
                      </div>
                    </div>
                    <div class="col-8 d-flex justify-content-start align-items-center">
                      <div class="foodstuff-name">
                          <p><%= pd.cooking_detail %></p>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-8 offset-2 col-md-4 offset-4 mt-3">
         <%= link_to '戻る', 'javascript:history.back()', class: 'btn btn-outline-secondary btn-block' %>
      </div>
    </div>
  </div>
</div>

app/views/manageownfoodstuffs/new.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12 col-md-8 offset-md-2 text-center mt-3">
        <div class="page-title m-0 d-inline">食材の追加</div>
        <div>(<%= link_to @cuisine.name, managecuisine_path(@cuisine) %>)</div>
      </div>
    </div>
    <div class="row mt-2">
      <div class="col-md-6 offset-md-3">
        <%= form_with(model: @foodstuff, url: manageownfoodstuffs_path, method: :post, local: true) do |form| %>
            <%= render 'layouts/flash_message' %>
            <%= render 'shared/error_messages', { resource: @foodstuff } if @foodstuff.errors.any? %>
            <%= render 'form', { form: form, cuisine: @cuisine } %>
            <div class="col-10 offset-1">
              <div class="text-center my-2">
                <%= link_to '未登録の材料を登録する', new_userrawmaterial_path, remote: true, class: 'text-muted', data: { toggle: 'modal', target: '#rawmaterialModal' } %>
              </div>
            <%= form.submit '追加する', class: 'btn btn-success btn-block' %>
            </div>
            <div class="col-10 offset-1 mt-2">
              <%= link_to '手順登録へ', new_manageownprocedure_path(cuisine_id: @cuisine.id), class: 'btn btn-outline-secondary btn-block' %>
            </div>
        <% end %>
        <!-- foodstuffs and procedure list -->
        <div class="mt-2">
          <ul class="nav nav-tabs nav-fill" role="tablist" id="fp-tab">
            <li class="nav-item" role="presentation">
              <a class="nav-link active" role="tab" data-toggle="tab" href="#tab1" id="tab-foodstuff">食材</a>
            </li>
            <li class="nav-item" role="presentation">
              <a class="nav-link" role="tab" data-toggle="tab" href="#tab2" id="tab-procedure">手順</a>
            </li>
          </ul>
          <div class="tab-content">
            <div class="tab-pane active" role="tabpanel" id="tab1">
            <% if @foodstuffs.present? %>
              <table id="table-sortable-procedure" class="table table-bordered table-hover mt-3">
                <tbody>
                  <%= render partial: 'foodstuff', collection: @foodstuffs, as: 'foodstuff' %>
                </tbody>
              </table>
            <% else %>
              <div class="text-center mt-3">
                <p>まだ登録がありません</p>
              </div>
            <% end %>
            </div>
            <div class="tab-pane" role="tabpanel" id="tab2">
              <div class="procedure-list">
                <% @procedures.each_with_index do |pd, idx| %>
                  <div class="row mt-3">
                    <div class="col-2 offset-1 d-flex justify-content-end align-items-center">
                      <div class="foodstuff-number">
                          <p><%= idx + 1 %>.</p>
                      </div>
                    </div>
                    <div class="col-8 d-flex justify-content-start align-items-center">
                      <div class="foodstuff-name">
                          <p><%= pd.cooking_detail %></p>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col text-center">
        <%= link_to 'もどる', 'javascript:history.back()', class: 'text-center text-black-50' %>
      </div>
    </div>
  </div>
</div>

<div id="rawmaterialModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
  </div>
</div>