config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # 管理者側
  devise_for :managers, controllers: {
    sessions: 'managers/sessions',
    passwords: 'managers/passwords',
    # TODO: 後で登録できないようにする
    registrations: 'managers/registrations'
  }

  devise_scope :manager do
    post 'login_as_guest_manager', to: 'managers/sessions#login_as_guest_manager'
  end
  namespace :managers do
    resources :cookedstates, except: [:show] do
      member do
        get 'restore'
      end
    end

    resources :cuisines
    resources :foodcategories, except: [:show]
    resources :foodstuffs, except: [:index, :show] do
      member do
        put :sort
      end
      collection do
        get 'search_foodcategory'
        get 'search_rawmaterial'
        get 'search_unit'
      end
    end

    resources :ingredients, except: [:show] do
      member do
        get 'restore'
      end
    end

    resources :procedures, except: [:index] do
      member do
        put :sort
      end
    end

    resources :rawmaterials do
      member do
        get 'restore'
      end
    end
    get 'dashboard', to: 'tops#dashboard'
    put 'toggle_editable', to: 'tops#toggle_editable', as: 'toggle_editable'
  end

  # ユーザー側
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'login_as_guest_user', to: 'users/sessions#login_as_guest_user'
  end
  resources :cookinghistorys, only: [:index, :destroy]
  resources :cuisines, only: [:show] do
    delete :remove_favorite
    delete :remove_menu
    delete :remove_from_todays_menus, action: :remove_from_todays_menus, controller: 'cookinghistorys'
    post :add_favorite
    post :add_menu
    post :add_to_todays_menu, action: :add_to_todays_menu, controller: 'cookinghistorys'
    collection do
      get :search
    end
  end
  resources :contacts, only: [:show, :new, :create]
  resources :favorites, only: [:index, :destroy]
  post '/add_todaysmenu/:cuisine_id', to: 'favorites#add_todaysmenu_from_favorite', as: 'add_todaysmenu_from_favorite'
  delete '/remove_todaysmenu/:cuisine_id', to: 'favorites#remove_todaysmenu_from_favorite', as: 'remove_todaysmenu_from_favorite'
  resources :keywords, only: [:index]
  resources :managecuisines do
    patch :toggle_status
  end
  resources :manageownfoodstuffs
  resources :manageownprocedures
  resources :userrawmaterials, only: [:index, :new, :create]
  resources :stocks, only: [:index, :new, :create, :destroy] do
    collection do
      get 'auto_today_create'
      get 'search_rawmaterial'
      get 'search_unit_and_expiry_period'
    end
  end
  resources :todaysmenus, only: [:index, :update, :destroy] do
    collection do
      post 'cooked_done'
    end
  end

  # TODO: 原材料から探せるようにする
  # get 'rawmaterials/search'
  get 'search/foodcategory_search', to: 'search#foodcategory_search'
  get 'search/rawmaterial_search', to: 'search#rawmaterial_search'
  get 'search/unit_search', to: 'search#unit_search'
  get '/about', to: 'tops#about'
  # get 'tops/index'
  get 'user/profile', to: 'users#show'
  put 'update_profile', to: 'users#update'

  root to: 'tops#index'

  # letter_opener_web
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/shared/_disp_file_path.html.erb
<% unless "#{controller.controller_path}/#{controller.action_name}" == "users/cuisines/show" %>
  <div>
    <p>
      <%= controller.controller_path %>/<%= controller.action_name %>.html.erb
    </p>
    <p id="browserWidth"></p>
  </div>
<% end %>

app/views/shared/_disp_time.html.erb
<% unless "#{controller.controller_path}/#{controller.action_name}" == "users/cuisines/show" %>
<div>
  現在時刻<br />
  <%= Time.zone.now %><br />
</div>
<% end %>

app/views/shared/_error_messages.html.erb
<%#
  TODO: 不要などで該当する箇所を置き換える
        不要になったら削除
%>
<div class="alert alert-danger" role="alert">
  <ul>
    <% resource.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_flash_messages.erb
<div class="mt-3">
  <% flash.each do |key, value| %>
    <% next if key == "timedout" %>
    <div class="alert alert-<%= bootstrap_alert(key) %>">
      <strong>
        <%= value %>
      </strong>
    </div>
  <% end %>
</div>

app/views/shared/_user_navbar.html.erb
<nav class='navbar navbar-light navbar-expand'>
  <div class='container'>
    <%= link_to @app_name, root_path, class: 'navbar-brand' %>
    <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarsExample02' aria-controls='navbarsExample02' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>
    <div class='collapse navbar-collapse' id='navbarsExample02'>
      <%= search_form_for @search, url: search_cuisines_path, html: { class: 'form-inline ml-auto my-2 my-md-0 d-none d-md-block' } do |f| %>
        <div class='input-group'>
          <%= f.search_field :name_or_description_or_rawmaterials_name_or_rawmaterials_hiragana_cont, class: 'form-control', type: 'search', placeholder: '食材、料理名など' %>
          <span class='input-group-append'>
            <%= f.button type: 'submit', style: 'border-style: none;' do %>
              <i class='fa fa-search'></i>
            <% end %>
        </div>
      <% end %>
      <ul class='navbar-nav ml-auto'>
        <li class='nav-item'>
          <%= link_to stocks_path, class: 'nav-link text-center stocks-tooltip', data: { toggle: 'tooltip', placement: 'bottom' }, title: '家にある食材' do %>
            <i class='fas fa-box'></i><span class='d-none d-lg-inline'>&nbsp;家の食材</span>
          <% end %>
        </li>
        <li class='nav-item'>
          <%= link_to cookinghistorys_path, class: 'nav-link text-center histories-tooltip', data: { toggle: 'tooltip', placement: 'bottom' }, title: '料理履歴' do %>
            <i class='fas fa-history'></i><span class='d-none d-lg-inline'>&nbsp;料理履歴</span>
          <% end %>
        </li>
        <li class='nav-item d-xl-flex align-items-xl-center'>
          <%= link_to todaysmenus_path, class: 'nav-link text-center todaysmenus-tooltip', data: { toggle: 'tooltip', placement: 'bottom' }, title: '今日の献立' do %>
            <i class='fas fa-concierge-bell'></i><span class='d-none d-lg-inline'>&nbsp;今日の献立</span>
          <% end %>
        </li>
        <li class='nav-item align-items-xl-center'>
          <%= link_to favorites_path, class: 'nav-link text-center favorites-tooltip', data: { toggle: 'tooltip', placement: 'bottom' }, title: 'お気に入り' do %>
          <i class='far fa-bookmark'></i><span class='d-none d-lg-inline'>&nbsp;お気に入り</span>
          <% end %>
        </li>
        <li class='nav-item dropdown d-none d-md-block'><a class='dropdown-toggle nav-link text-center' data-toggle='dropdown' aria-expanded='false' href='#'><i class='fas fa-user-alt fa-lg user-icon'></i></a>
          <div class='dropdown-menu dropdown-menu-right'>
            <% if user_signed_in? %>
              <%= link_to 'マイページ', user_profile_path, class: 'dropdown-item text-center' %>
              <%= link_to 'あなたのレシピ', managecuisines_path, class: 'dropdown-item text-center' %>
              <%= link_to 'レシピを登録', new_managecuisine_path, class: 'dropdown-item text-center' %>
              <%= link_to 'お問い合わせ', new_contact_path, class: 'dropdown-item text-center' %>
              <%= link_to 'このサイトについて', about_path, class: 'dropdown-item text-center' %>
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'dropdown-item text-center' %>
            <% else %>
              <%= link_to 'このサイトについて', about_path, class: 'dropdown-item text-center' %>
              <%= link_to 'ログイン', new_user_session_path, class: 'dropdown-item text-center' %>
              <%= link_to '新規登録', new_user_registration_path, class: 'dropdown-item text-center' %>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

<nav class='navbar navbar-expand-lg navbar-light d-md-none'>
  <%= search_form_for @search, url: search_cuisines_path do |f| %>
    <div class='input-group'>
      <%= f.search_field :name_or_description_or_rawmaterials_name_or_rawmaterials_hiragana_cont, class: 'form-control', type: 'search', placeholder: '食材、料理名など' %>
      <span class='input-group-append'>
        <%= f.button type: 'submit', style: 'border-style: none;' do %>
          <i class='fa fa-search'></i>
        <% end %>
      </div>
    </div>
  <% end %>
  <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarNavDropdown' aria-controls='navbarNavDropdown' aria-expanded='false' aria-label='Toggle navigation'>
    <i class='fas fa-user-alt fa-lg user-icon'></i>
  </button>
  <div class='collapse navbar-collapse' id='navbarNavDropdown'>
    <ul class='navbar-nav'>
      <li class='nav-item'>
          <% if user_signed_in? %>
            <%= link_to 'マイページ', user_profile_path, class: 'nav-link text-center' %>
            <%= link_to 'あなたのレシピ', managecuisines_path, class: 'nav-link text-center' %>
            <%= link_to 'レシピを登録', new_managecuisine_path, class: 'nav-link text-center' %>
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link text-center' %>
          <% else %>
            <%= link_to 'ログイン', new_user_session_path, class: 'nav-link text-center' %>
            <%= link_to '新規登録', new_user_registration_path, class: 'nav-link text-center' %>
          <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_user_settings_sidebar.html.erb
<div class="col-12 col-sm-4 col-md-3 offset-md-1 offset-lg-2 d-xl-flex align-items-xl-center px-2 mt-2">
  <div id="items">
    <div class="text-center">
      <% unless @user.profile_image.blank? %>
        <%= image_tag @user.profile_image.url, class: 'rounded-circle img-fluid' %>
      <% else %>
        <%= image_pack_tag 'no_avatar.jpg', class: 'rounded-circle img-fluid' %>
      <% end %>
      <% unless @user.nickname.blank? %>
        <p><%= @user.nickname %><br />さん</p>
      <% end %>
    </div>
    <div>
      <ul class="list-group mt-2">
        <li class="list-group-item">
          <span>
            <%= link_to 'ユーザー情報', user_profile_path, class: add_class_to_text(@current_page, 'users#show').to_s %>
          </span>
        </li>
        <li class="list-group-item">
          <%= link_to '退会する', user_registration_path,
                      class: 'text-black-50',
                      data: {
                        confirm: "<i class='fas fa-exclamation-circle'></i>
                    アカウントを削除します。よろしいですか?<br><small>※ お使いのアカウント情報を削除すると全てのサービスがご利用できなくなります。再度ご利用いただくには再登録していただく必要がございます。</small>",
                        cancel: 'キャンセル',
                        commit: '削除',
                        title: 'アカウント削除'
                      },
                      role: 'button',
                      method: :delete, local: true %>
          <span class="text-black-50">
          </span>
        </li>
      </ul>
    </div>
  </div>
</div>