config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # 管理者側
  devise_for :managers, controllers: {
    sessions: 'managers/sessions',
    passwords: 'managers/passwords',
    # TODO: 後で登録できないようにする
    registrations: 'managers/registrations'
  }

  devise_scope :manager do
    post 'login_as_guest_manager', to: 'managers/sessions#login_as_guest_manager'
  end
  namespace :managers do
    resources :cookedstates, except: [:show] do
      member do
        get 'restore'
      end
    end

    resources :cuisines
    resources :foodcategories, except: [:show]
    resources :foodstuffs, except: [:index, :show] do
      member do
        put :sort
      end
      collection do
        get 'search_foodcategory'
        get 'search_rawmaterial'
        get 'search_unit'
      end
    end

    resources :ingredients, except: [:show] do
      member do
        get 'restore'
      end
    end

    resources :procedures, except: [:index] do
      member do
        put :sort
      end
    end

    resources :rawmaterials do
      member do
        get 'restore'
      end
    end
    get 'dashboard', to: 'tops#dashboard'
    put 'toggle_editable', to: 'tops#toggle_editable', as: 'toggle_editable'
  end

  # ユーザー側
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'login_as_guest_user', to: 'users/sessions#login_as_guest_user'
  end
  resources :cookinghistorys, only: [:index, :destroy]
  resources :cuisines, only: [:show] do
    delete :remove_favorite
    delete :remove_menu
    delete :remove_from_todays_menus, action: :remove_from_todays_menus, controller: 'cookinghistorys'
    post :add_favorite
    post :add_menu
    post :add_to_todays_menu, action: :add_to_todays_menu, controller: 'cookinghistorys'
    collection do
      get :search
    end
  end
  resources :contacts, only: [:show, :new, :create]
  resources :favorites, only: [:index, :destroy]
  post '/add_todaysmenu/:cuisine_id', to: 'favorites#add_todaysmenu_from_favorite', as: 'add_todaysmenu_from_favorite'
  delete '/remove_todaysmenu/:cuisine_id', to: 'favorites#remove_todaysmenu_from_favorite', as: 'remove_todaysmenu_from_favorite'
  resources :keywords, only: [:index]
  resources :managecuisines do
    patch :toggle_status
  end
  resources :manageownfoodstuffs
  resources :manageownprocedures
  resources :userrawmaterials, only: [:index, :new, :create]
  resources :stocks, only: [:index, :new, :create, :destroy] do
    collection do
      get 'auto_today_create'
      get 'search_rawmaterial'
      get 'search_unit_and_expiry_period'
    end
  end
  resources :todaysmenus, only: [:index, :update, :destroy] do
    collection do
      post 'cooked_done'
    end
  end

  # TODO: 原材料から探せるようにする
  # get 'rawmaterials/search'
  get 'search/foodcategory_search', to: 'search#foodcategory_search'
  get 'search/rawmaterial_search', to: 'search#rawmaterial_search'
  get 'search/unit_search', to: 'search#unit_search'
  get '/about', to: 'tops#about'
  # get 'tops/index'
  get 'user/profile', to: 'users#show'
  put 'update_profile', to: 'users#update'

  root to: 'tops#index'

  # letter_opener_web
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/cuisines_controller.rb
# frozen_string_literal: true

class CuisinesController < ApplicationController
  def show
    @cuisine = Cuisine.find(params[:id])
    @foodstuffs = Foodstuff.includes(:rawmaterial, { rawmaterial: :unit }).where(cuisine_id: @cuisine.id)
    # @genres
    # TODO: あとでGenre, Tags機能を実装した時に @genres, @tagsを追加する
    @procedures = Procedure.where(cuisine_id: @cuisine.id)
  end

  def add_favorite
    @favorite = current_user.favorites.build(cuisine_id: params[:cuisine_id])
    @favorite.save
    @cuisine = Cuisine.find_by(id: params[:cuisine_id])
  end

  def add_menu
    @todaysmenu = current_user.todaysmenus.build(cuisine_id: params[:cuisine_id])
    @todaysmenu.save
    @cuisine = Cuisine.find_by(id: params[:cuisine_id])
  end

  def remove_favorite
    @favorite = current_user.favorites.find_by(cuisine_id: params[:cuisine_id])
    @favorite.destroy
    @cuisine = Cuisine.find_by(id: params[:cuisine_id])
  end

  # TODO: create_atを削除する
  def remove_menu
    @todaysmenu = current_user.todaysmenus.find_by(cuisine_id: params[:cuisine_id], created_at: Time.zone.now.all_day)
    @todaysmenu.destroy
    @cuisine = Cuisine.find_by(id: params[:cuisine_id])
  end

  def search
    @cuisines = @search.result.includes(:user).distinct.page(params[:page]).per(5)
  end
end

app/controllers/managers/confirmations_controller.rb
# frozen_string_literal: true

class Managers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/managers/cuisines_controller.rb
# frozen_string_literal: true

class Managers::CuisinesController < ApplicationController
  before_action :authenticate_manager!
  before_action :set_cuisine, only: %i[update edit destroy]
  layout 'manager'
  KAMINARI_PAGINATION_COUNT = 7

  def index
    @q = Cuisine.ransack(params[:q])
    @cuisines = @q.result.page(params[:page]).per(KAMINARI_PAGINATION_COUNT)
  end

  def show
    @cuisine = Cuisine.find(params[:id])
    @foodstuffs = Foodstuff.includes(rawmaterial: :unit).where(cuisine_id: @cuisine.id).rank(:row_order)
    @procedures = Procedure.where(cuisine_id: @cuisine.id).rank(:row_order)
  end

  def new
    @cuisine = Cuisine.new
  end

  def edit; end

  def create
    @cuisine = Cuisine.new(cuisine_params)
    if @cuisine.save
      redirect_to new_managers_foodstuff_path(cuisine_id: @cuisine.id), flash: { notice: "#{@cuisine.name} が作成されました" }
    else
      render 'new'
    end
  end

  def update
    if @cuisine.update(cuisine_params)
      redirect_to managers_cuisine_path(@cuisine), flash: { notice: '変更されました' }
    else
      render 'edit'
    end
  end

  def destroy
    @cuisine.destroy
    redirect_to managers_cuisines_path, flash: { notice: "#{@cuisine.name} が削除されました" }
  end

  private

  def set_cuisine
    @cuisine = Cuisine.find(params[:id])
  end

  def cuisine_params
    params.require(:cuisine).permit(:name, :genre, :calories, :cooking_time, :description, :main_image, :status)
  end
end

app/controllers/managers/foodcategories_controller.rb
# frozen_string_literal: true

class Managers::FoodcategoriesController < ApplicationController
  before_action :authenticate_manager!
  before_action :set_foodcategory, only: %i[update edit destroy]
  layout 'manager'
  KAMINARI_PAGINATION_COUNT = 13

  def index
    @q = Foodcategory.ransack(params[:q])
    @foodcategories = @q.result.page(params[:page]).per(KAMINARI_PAGINATION_COUNT)
  end

  def new
    @foodcategory = Foodcategory.new
  end

  def edit; end

  def create
    @foodcategory = Foodcategory.new(foodcategory_params)
    if @foodcategory.save
      redirect_to managers_foodcategories_path, flash: { notice: "#{@foodcategory.name} が作成されました" }
    else
      render 'new'
    end
  end

  def update
    if @foodcategory.update(foodcategory_params)
      redirect_to managers_foodcategories_path, flash: { notice: '変更されました' }
    else
      render 'edit'
    end
  end

  def destroy
    @foodcategory.destroy
    redirect_to managers_foodcategories_path, flash: { notice: "#{@foodcategory.name} が削除されました" }
  end

  private

  def set_foodcategory
    @foodcategory = Foodcategory.find(params[:id])
  end

  def foodcategory_params
    params.require(:foodcategory).permit(:name)
  end
end

app/controllers/managers/foodstuffs_controller.rb
# frozen_string_literal: true

class Managers::FoodstuffsController < ApplicationController
  before_action :authenticate_manager!
  before_action :set_foodstuff, only: %i[update edit destroy restore]
  layout 'manager'

  def index
    @foodstuffs = Foodstuff.includes({ rawmaterial: :unit })
  end

  def new
    # HACK: ここの無理やり感をなんとかしたい
    @cuisine = Cuisine.find(params[:cuisine_id])
    @foodstuff = Foodstuff.new
  end

  def edit
    @cuisine = Cuisine.find(params[:cuisine_id])
  end

  def create
    @foodstuff = Foodstuff.new(foodstuff_params)
    if @foodstuff.save
      redirect_to new_managers_foodstuff_path(cuisine_id: @foodstuff.cuisine_id), flash: { notice: "#{@foodstuff.rawmaterial.name} が追加されました" }
    else
      # HACK: render 'new'を使ってもうちょっと上手く書きたい
      # redirect_to new_managers_foodstuff_path(cuisine_id: @foodstuff.cuisine_id), flash: { error: @foodstuff.errors.full_messages.to_s }
      @cuisine = Cuisine.find(@foodstuff.cuisine_id)
      params[:cuisine_id] = @foodstuff.cuisine_id
      render 'new'
    end
  end

  def update
    if @foodstuff.update(foodstuff_params)
      redirect_to managers_cuisine_path(@foodstuff.cuisine_id), flash: { notice: '変更されました' }
    else
      # HACK: もうちょっと上手い書き方がありそう
      params[:cuisine_id] = @foodstuff.cuisine_id
      render 'edit'
    end
  end

  def destroy
    @foodstuff.destroy
    redirect_to new_managers_foodstuff_path(cuisine_id: @foodstuff.cuisine_id), flash: { notice: "#{@foodstuff.rawmaterial.name} が削除されました" }
  end

  def restore
    @foodstuff.undiscard
    redirect_to managers_foodstuffs_path, flash: { notice: "#{@foodstuff} が復元されました" }
  end

  def sort
    @foodstuff = Foodstuff.find(params[:id])
    @foodstuff.update(foodstuff_params)
    head :ok
  end

  def search_rawmaterial
    @rawmaterials = Rawmaterial.where('name LIKE ? OR hiragana LIKE ?', "%#{params[:q]}%", "%#{params[:q]}%")
    respond_to do |format|
      format.json { render json: @rawmaterials }
    end
  end

  def search_unit
    @unit = Rawmaterial.find_by(id: params[:rm_id])&.unit
    respond_to do |format|
      format.json { render json: @unit }
    end
  end

  def search_foodcategory
    foodcategory_id = Rawmaterial.find_by(id: params[:rm_id]).foodcategory_id
    respond_to do |format|
      format.json { render json: foodcategory_id }
    end
  end

  private

  def set_foodstuff
    @foodstuff = Foodstuff.find(params[:id])
  end

  def foodstuff_params
    params.require(:foodstuff).permit(:id, :quantity, :cuisine_id, :rawmaterial_id, :row_order_position)
  end
end

app/controllers/managers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Managers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/managers/passwords_controller.rb
# frozen_string_literal: true

class Managers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/managers/procedures_controller.rb
# frozen_string_literal: true

class Managers::ProceduresController < ApplicationController
  before_action :authenticate_manager!
  before_action :set_procedure, only: %i[edit update destroy]
  layout 'manager'

  def new
    @procedure = Procedure.new
    set_cuisine_and_registerd_pds
  end

  def edit
    set_cuisine_and_registerd_pds
  end

  def create
    @procedure = Procedure.new(procedure_params)
    if @procedure.save
      redirect_to new_managers_procedure_path(cuisine_id: @procedure.cuisine_id), flash: { notice: '手順が追加されました' }
    else
      params[:cuisine_id] = @procedure.cuisine_id
      set_cuisine_and_registerd_pds
      render 'new'
    end
  end

  def update
    if @procedure.update(procedure_params)
      redirect_to new_managers_procedure_path(cuisine_id: @procedure.cuisine_id), flash: { notice: '更新されました' }
    else
      set_cuisine_and_registerd_pds
      render 'edit'
    end
  end

  def destroy
    @procedure.destroy
    case params[:action_name]
    when 'new', 'edit'
      redirect_to new_managers_procedure_path(cuisine_id: @procedure.cuisine_id), flash: { notice: '削除しました' }
    when 'show'
      redirect_to managers_cuisine_path(@procedure.cuisine_id), flash: { notice: '手順を削除しました' }
    end
  end

  def sort
    @procedure = Procedure.find(params[:id])
    @procedure.update(procedure_params)
    head :ok
  end

  private

  def set_procedure
    @procedure = Procedure.find(params[:id])
  end

  def set_cuisine_and_registerd_pds
    @cuisine = Cuisine.find(params[:cuisine_id])
    @registered_procedures = Procedure.where(cuisine_id: params[:cuisine_id]).rank(:row_order)
  end

  def procedure_params
    params.require(:procedure).permit(:cooking_detail, :cuisine_id, :row_order_position)
  end
end

app/controllers/managers/rawmaterials_controller.rb
# frozen_string_literal: true

class Managers::RawmaterialsController < ApplicationController
  before_action :authenticate_manager!
  before_action :set_rawmaterial, only: %i[edit update destroy]
  layout 'manager'
  KAMINARI_PAGINATION_COUNT = 13

  def index
    @q = Rawmaterial.includes(:foodcategory).ransack(params[:q])
    @rawmaterials = @q.result.page(params[:page]).per(KAMINARI_PAGINATION_COUNT)
  end

  def new
    @rawmaterial = Rawmaterial.new
  end

  def edit; end

  def create
    @rawmaterial = Rawmaterial.new(rawmaterial_params)
    if @rawmaterial.save
      redirect_to managers_rawmaterials_path, flash: { notice: "食材区分 #{@rawmaterial.name} が作成されました" }
    else
      render 'new'
    end
  end

  def update
    if @rawmaterial.update(rawmaterial_params)
      redirect_to managers_rawmaterials_path, flash: { notice: '変更されました' }
    else
      render 'edit'
    end
  end

  def destroy
    @rawmaterial&.destroy
    redirect_to managers_rawmaterials_path, flash: { notice: "原材料 #{@rawmaterial.name} が削除されました" }
  end

  private

  def set_rawmaterial
    @rawmaterial = Rawmaterial.find(params[:id])
  end

  def rawmaterial_params
    params.require(:rawmaterial).permit(:name, :hiragana, :unit_id, :foodcategory_id, :expiry_period, :user_id)
  end
end

app/controllers/managers/sessions_controller.rb
# frozen_string_literal: true

class Managers::SessionsController < Devise::SessionsController
  layout 'manager_sign_in'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(_resource)
    managers_dashboard_path
  end

  def after_sign_out_path_for(_resource)
    new_manager_session_path
  end

  def login_as_guest_manager
    guest_manager = Manager.create_account_as_guest
    sign_in guest_manager
    redirect_to managers_dashboard_path, notice: "#{guest_manager.name}としてログインしました"
  end
end

app/helpers/cuisines_helper.rb
# frozen_string_literal: true

module CuisinesHelper
  def owner_name(cuisine)
    if cuisine.user.present?
      "by #{cuisine.user.nickname}さん"
    else
      '退会user'
    end
  end

  def disp_foodstuff(instance)
    if instance.ingredient_id.present? && instance.cookedstate_id.present?
      "#{instance.rawmaterial.name}#{instance.ingredient.name}#{instance.cookedstate.name}"
    elsif instance.ingredient_id.present?
      "#{instance.rawmaterial.name}#{instance.ingredient.name}"
    else
      instance.rawmaterial.name.to_s
    end
  end

  def disp_quantity(instance)
    "#{instance.quantity}#{instance.unit.name}"
  end
end

app/helpers/managers/cuisines_helper.rb
# frozen_string_literal: true

module Managers::CuisinesHelper
  def disp_cookedstate_name(instance)
    instance.cookedstate.name.to_s if instance.cookedstate_id.present?
  end
end

app/helpers/managers/foodcategories_helper.rb
# frozen_string_literal: true

module Managers::FoodcategoriesHelper
end

app/helpers/managers/foodstuffs_helper.rb
# frozen_string_literal: true

module Managers::FoodstuffsHelper
  def disp_cookedstate_name(instance)
    instance.cookedstate.name.to_s if instance.cookedstate_id.present?
  end
end

app/helpers/managers/procedures_helper.rb
# frozen_string_literal: true

module Managers::ProceduresHelper
end

app/views/managers/cuisines/_cuisine.html.erb
<tr>
  <td class="align-middle">
    <% if cuisine.main_image.present? %>
      <%= image_tag cuisine.main_image.url, size: '70x70' %>
    <% else %>
      <%= image_pack_tag 'no_image_100x100.jpg', size: '70x70' %>
    <% end %>
  </td>
  <td class="align-middle"><%= cuisine.name %></td>
  <td class="align-middle"><%= cuisine.cooking_time_i18n %></td>
  <td class="align-middle"><%= cuisine.created_at %></td>
  <td class="align-middle">
    <%= link_to managers_cuisine_path(cuisine.id), class: 'btn btn-default' do %>
      <i class="far fa-eye"></i>
    <% end %>
    <% if current_manager.editable? %>
      <%= link_to managers_cuisine_path(cuisine.id),
                  class: 'btn btn-default',
                  data: {
                    confirm: "「#{cuisine.name}」を削除しますか?",
                    cansel: 'キャンセル',
                    commit: '削除',
                    title: '削除確認'
                  },
                  method: :delete do %>
        <i class="far fa-trash-alt"></i>
      <% end %>
    <% else %>
      <button type='button' class='btn btn-default manager-cuisines-tooltip' data-toggle='tooltip' data-placement='top' title='サイト運営者以外は削除できません' disabled><i class='far fa-trash-alt'></i></button>
    <% end %>
  </td>
</tr>

app/views/managers/cuisines/_cuisines.html.erb
<table class="table table-hover table-sm table-responsive">
  <thead>
    <tr>
      <td class="align-middle"><%= sort_link(@q, :id, 'ID') %></td>
      <td class="align-middle">メイン画像</td>
      <td class="align-middle text-center"><%= sort_link(@q, :name, '料理レシピ名') %></td>
      <td class="align-middle"><%= sort_link(@q, :difficulty, 'お手軽度') %></td>
      <td class="align-middle"><%= sort_link(@q, :cooking_time, '調理時間(分)') %></td>
      <td class="align-middle text-center"><%= sort_link(@q, :created_at, '登録日') %></td>
      <td class="align-middle"></td>
      <td class="align-middle"></td>
    </tr>
  </thead>
  <tbody>
    <% @cuisines.each do |cn| %>
    <% if cn.present? %>
    <tr>
      <td class="align-middle"><%= cn.id %></td>
      <% if cn.main_image.present? %>
      <td>
        <%# cn.main_image %>
        <%= image_tag cn.main_image.url, size: '70x70' %>
      </td>
      <% else %>
      <td> 未登録 </td>
      <% end %>
      <td class="align-middle"><%= cn.name %></td>
      <td class="align-middle"><%= cn.difficulty_i18n %></td>
      <td class="align-middle text-center"><%= cn.cooking_time %></td>
      <td class="align-middle"><%= cn.created_at %></td>
      <td class="align-middle">
        <%= link_to managers_cuisine_path(cn.id),  class: "page-link text-dark d-inline-block", role: "button" do %>
        <i class="far fa-eye"></i>
        <% end %>
      </td>
      <td class="align-middle">
        <%= link_to edit_managers_cuisine_path(cn.id),
              class: "page-link text-dark d-inline-block",
              role: "button" do %>
          <i class="fas fa-pen"></i>
        <% end %>
      </td>
      <td class="align-middle">
        <%= link_to managers_cuisine_path(cn.id),
              class: "page-link text-dark d-inline-block",
              data: {
                confirm: "<i class='fas fa-exclamation-circle'></i>
                  本当に「<strong>#{cn.name}</strong>」を削除しますか?",
                cansel: "キャンセル",
                commit: "削除",
                title: "削除確認"
              },
              role: "button",
              method: :delete do %>
          <i class="far fa-trash-alt"></i>
        <% end %>
      </td>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
<div class="row">
  <div class="col">
    <%= page_entries_info @cuisines %>
  </div>
  <div class="col">
    <%= paginate @cuisines, theme: 'twitter-bootstrap-4',
                          pagination_class: "pagination-sm",
                          nav_class: "d-inline-b"
    %>
  </div>
</div>

app/views/managers/cuisines/_foodstuff.html.erb
<tr class="foodstuff" data-model_name="<%= foodstuff.class.name.underscore %>" <%= sort_managers_foodstuff_path(foodstuff) %> ">
  <td><%= foodstuff.rawmaterial.name %></td>
  <td><%= foodstuff.quantity %><%= foodstuff.rawmaterial.unit.name unless foodstuff.quantity.start_with?('適量', '少々', 'お好みで') %></td>
  <td>
    <% if current_manager.email == ENV['TOMAIL'] %>
      <%= link_to edit_managers_foodstuff_path(id: foodstuff.id, cuisine_id: foodstuff.cuisine_id), class: 'btn btn-default btn-lg' do %>
      <i class=" fas fa-pen "></i>
      <% end %>
      <%= link_to managers_foodstuff_path(foodstuff.id), class: 'btn btn-default btn-lg', method: :delete do %>
      <i class=" far fa-trash-alt "></i>
      <% end %>
    <% else %>
      <button type='button' class='btn btn-default manager-cuisine-tooltip' data-toggle='tooltip' data-placement='top' title='サイト運営者以外は変更できません' disabled><i class=" fas fa-pen "></i></button>
      <button type='button' class='btn btn-default manager-cuisine-tooltip' data-toggle='tooltip' data-placement='top' title='サイト運営者以外は削除できません' disabled><i class='far fa-trash-alt'></i></button>
    <% end %>
  </td>
</tr>

app/views/managers/cuisines/_procedure.html.erb
<tr class="procedure" data-model_name="<%= procedure.class.name.underscore %>" <%= sort_managers_procedure_path(procedure) %> ">
  <td><%= procedure.cooking_detail %></td>
  <td>
    <% if current_manager.editable? %>
      <%= link_to edit_managers_procedure_path(procedure.id, cuisine_id: @cuisine.id), class: 'page-link text-dark d-inline-block', role: 'button', local: true do %>
      <i class=" fas fa-pen "></i>
      <% end %>
      <%= link_to managers_procedure_path(procedure.id, action_name: 'show', current_procedure_id: procedure.id), class: 'page-link text-dark d-inline-block', role: 'button', method: :delete do %>
      <i class=" far fa-trash-alt "></i>
      <% end %>
    <% else %>
      <button type='button' class='btn btn-default manager-cuisine-tooltip' data-toggle='tooltip' data-placement='top' title='サイト運営者以外は変更できません' disabled><i class=" fas fa-pen "></i></button>
      <button type='button' class='btn btn-default manager-cuisine-tooltip' data-toggle='tooltip' data-placement='top' title='サイト運営者以外は削除できません' disabled><i class='far fa-trash-alt'></i></button>
    <% end %>
  </td>
</tr>

app/views/managers/cuisines/index.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div>
      <%= render 'layouts/flash_message' %>
    </div>
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 d-inline">料理レシピ一覧</h1>
        <% if current_manager.editable? %>
          <%= link_to new_managers_cuisine_path, class: 'btn btn-info ml-2', role: 'button' do %>
            <i class="fas fa-plus"></i> 追加する
          <% end %>
        <% end %>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item">
            <%= link_to 'Home', managers_dashboard_path, { class: 'text-muted' } %>
          </li>
          <li class="breadcrumb-item active">料理レシピ一覧(データ一覧)</li>
        </ol>
      </div>
    </div>
  </div>
</div>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <div>
              <div class="row">
                <div class="col-sm-12 col-md-6"></div>
                <div class="col-sm-12 col-md-6"></div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <% if @cuisines.present? %>
                    <table class="table table-bordered table-hover">
                      <thead>
                        <tr>
                          <th class="align-middle">メイン画像</th>
                          <th class="align-middle"><%= sort_link(@q, :name, '料理レシピ名', default_order: :desc) %></th>
                          <th class="align-middle"><%= sort_link(@q, :cooking_time, '調理時間(分)', default_order: :desc) %></th>
                          <th class="align-middle"><%= sort_link(@q, :created_at, '登録日', default_order: :desc) %></th>
                          <th style="width: 15%;"></th>
                        </tr>
                      </thead>
                      <tbody>
                        <%= render partial: 'cuisine', collection: @cuisines, as: 'cuisine' %>
                      </tbody>
                    </table>
                  <% else %>
                    <div class="text-center">
                      <p>まだ登録がありません</p>
                    </div>
                  <% end %>
                </div>
              </div>
              <% if @cuisines.present? %>
              <div class="row">
                <div class="col-sm-12 col-md-5">
                  <div class="dataTables_info" id="example2_info" role="status" aria-live="polite"><%= page_entries_info @cuisines %>
                  </div>
                </div>
                <div class="col-sm-12 col-md-7 d-flex justify-content-center">
                  <%= paginate @cuisines, theme: 'twitter-bootstrap-4',
                                          pagination_class: 'pagination-sm',
                                          nav_class: 'd-inline-b' %>
                </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>