config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # 管理者側
  devise_for :managers, controllers: {
    sessions: 'managers/sessions',
    passwords: 'managers/passwords',
    # TODO: 後で登録できないようにする
    registrations: 'managers/registrations'
  }

  devise_scope :manager do
    post 'login_as_guest_manager', to: 'managers/sessions#login_as_guest_manager'
  end
  namespace :managers do
    resources :cookedstates, except: [:show] do
      member do
        get 'restore'
      end
    end

    resources :cuisines
    resources :foodcategories, except: [:show]
    resources :foodstuffs, except: [:index, :show] do
      member do
        put :sort
      end
      collection do
        get 'search_foodcategory'
        get 'search_rawmaterial'
        get 'search_unit'
      end
    end

    resources :ingredients, except: [:show] do
      member do
        get 'restore'
      end
    end

    resources :procedures, except: [:index] do
      member do
        put :sort
      end
    end

    resources :rawmaterials do
      member do
        get 'restore'
      end
    end
    get 'dashboard', to: 'tops#dashboard'
    put 'toggle_editable', to: 'tops#toggle_editable', as: 'toggle_editable'
  end

  # ユーザー側
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'login_as_guest_user', to: 'users/sessions#login_as_guest_user'
  end
  resources :cookinghistorys, only: [:index, :destroy]
  resources :cuisines, only: [:show] do
    delete :remove_favorite
    delete :remove_menu
    delete :remove_from_todays_menus, action: :remove_from_todays_menus, controller: 'cookinghistorys'
    post :add_favorite
    post :add_menu
    post :add_to_todays_menu, action: :add_to_todays_menu, controller: 'cookinghistorys'
    collection do
      get :search
    end
  end
  resources :contacts, only: [:show, :new, :create]
  resources :favorites, only: [:index, :destroy]
  post '/add_todaysmenu/:cuisine_id', to: 'favorites#add_todaysmenu_from_favorite', as: 'add_todaysmenu_from_favorite'
  delete '/remove_todaysmenu/:cuisine_id', to: 'favorites#remove_todaysmenu_from_favorite', as: 'remove_todaysmenu_from_favorite'
  resources :keywords, only: [:index]
  resources :managecuisines do
    patch :toggle_status
  end
  resources :manageownfoodstuffs
  resources :manageownprocedures
  resources :userrawmaterials, only: [:index, :new, :create]
  resources :stocks, only: [:index, :new, :create, :destroy] do
    collection do
      get 'auto_today_create'
      get 'search_rawmaterial'
      get 'search_unit_and_expiry_period'
    end
  end
  resources :todaysmenus, only: [:index, :update, :destroy] do
    collection do
      post 'cooked_done'
    end
  end

  # TODO: 原材料から探せるようにする
  # get 'rawmaterials/search'
  get 'search/foodcategory_search', to: 'search#foodcategory_search'
  get 'search/rawmaterial_search', to: 'search#rawmaterial_search'
  get 'search/unit_search', to: 'search#unit_search'
  get '/about', to: 'tops#about'
  # get 'tops/index'
  get 'user/profile', to: 'users#show'
  put 'update_profile', to: 'users#update'

  root to: 'tops#index'

  # letter_opener_web
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/managers/confirmations_controller.rb
# frozen_string_literal: true

class Managers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/managers/cuisines_controller.rb
# frozen_string_literal: true

class Managers::CuisinesController < ApplicationController
  before_action :authenticate_manager!
  before_action :set_cuisine, only: %i[update edit destroy]
  layout 'manager'
  KAMINARI_PAGINATION_COUNT = 7

  def index
    @q = Cuisine.ransack(params[:q])
    @cuisines = @q.result.page(params[:page]).per(KAMINARI_PAGINATION_COUNT)
  end

  def show
    @cuisine = Cuisine.find(params[:id])
    @foodstuffs = Foodstuff.includes(rawmaterial: :unit).where(cuisine_id: @cuisine.id).rank(:row_order)
    @procedures = Procedure.where(cuisine_id: @cuisine.id).rank(:row_order)
  end

  def new
    @cuisine = Cuisine.new
  end

  def edit; end

  def create
    @cuisine = Cuisine.new(cuisine_params)
    if @cuisine.save
      redirect_to new_managers_foodstuff_path(cuisine_id: @cuisine.id), flash: { notice: "#{@cuisine.name} が作成されました" }
    else
      render 'new'
    end
  end

  def update
    if @cuisine.update(cuisine_params)
      redirect_to managers_cuisine_path(@cuisine), flash: { notice: '変更されました' }
    else
      render 'edit'
    end
  end

  def destroy
    @cuisine.destroy
    redirect_to managers_cuisines_path, flash: { notice: "#{@cuisine.name} が削除されました" }
  end

  private

  def set_cuisine
    @cuisine = Cuisine.find(params[:id])
  end

  def cuisine_params
    params.require(:cuisine).permit(:name, :genre, :calories, :cooking_time, :description, :main_image, :status)
  end
end

app/controllers/managers/foodcategories_controller.rb
# frozen_string_literal: true

class Managers::FoodcategoriesController < ApplicationController
  before_action :authenticate_manager!
  before_action :set_foodcategory, only: %i[update edit destroy]
  layout 'manager'
  KAMINARI_PAGINATION_COUNT = 13

  def index
    @q = Foodcategory.ransack(params[:q])
    @foodcategories = @q.result.page(params[:page]).per(KAMINARI_PAGINATION_COUNT)
  end

  def new
    @foodcategory = Foodcategory.new
  end

  def edit; end

  def create
    @foodcategory = Foodcategory.new(foodcategory_params)
    if @foodcategory.save
      redirect_to managers_foodcategories_path, flash: { notice: "#{@foodcategory.name} が作成されました" }
    else
      render 'new'
    end
  end

  def update
    if @foodcategory.update(foodcategory_params)
      redirect_to managers_foodcategories_path, flash: { notice: '変更されました' }
    else
      render 'edit'
    end
  end

  def destroy
    @foodcategory.destroy
    redirect_to managers_foodcategories_path, flash: { notice: "#{@foodcategory.name} が削除されました" }
  end

  private

  def set_foodcategory
    @foodcategory = Foodcategory.find(params[:id])
  end

  def foodcategory_params
    params.require(:foodcategory).permit(:name)
  end
end

app/controllers/managers/foodstuffs_controller.rb
# frozen_string_literal: true

class Managers::FoodstuffsController < ApplicationController
  before_action :authenticate_manager!
  before_action :set_foodstuff, only: %i[update edit destroy restore]
  layout 'manager'

  def index
    @foodstuffs = Foodstuff.includes({ rawmaterial: :unit })
  end

  def new
    # HACK: ここの無理やり感をなんとかしたい
    @cuisine = Cuisine.find(params[:cuisine_id])
    @foodstuff = Foodstuff.new
  end

  def edit
    @cuisine = Cuisine.find(params[:cuisine_id])
  end

  def create
    @foodstuff = Foodstuff.new(foodstuff_params)
    if @foodstuff.save
      redirect_to new_managers_foodstuff_path(cuisine_id: @foodstuff.cuisine_id), flash: { notice: "#{@foodstuff.rawmaterial.name} が追加されました" }
    else
      # HACK: render 'new'を使ってもうちょっと上手く書きたい
      # redirect_to new_managers_foodstuff_path(cuisine_id: @foodstuff.cuisine_id), flash: { error: @foodstuff.errors.full_messages.to_s }
      @cuisine = Cuisine.find(@foodstuff.cuisine_id)
      params[:cuisine_id] = @foodstuff.cuisine_id
      render 'new'
    end
  end

  def update
    if @foodstuff.update(foodstuff_params)
      redirect_to managers_cuisine_path(@foodstuff.cuisine_id), flash: { notice: '変更されました' }
    else
      # HACK: もうちょっと上手い書き方がありそう
      params[:cuisine_id] = @foodstuff.cuisine_id
      render 'edit'
    end
  end

  def destroy
    @foodstuff.destroy
    redirect_to new_managers_foodstuff_path(cuisine_id: @foodstuff.cuisine_id), flash: { notice: "#{@foodstuff.rawmaterial.name} が削除されました" }
  end

  def restore
    @foodstuff.undiscard
    redirect_to managers_foodstuffs_path, flash: { notice: "#{@foodstuff} が復元されました" }
  end

  def sort
    @foodstuff = Foodstuff.find(params[:id])
    @foodstuff.update(foodstuff_params)
    head :ok
  end

  def search_rawmaterial
    @rawmaterials = Rawmaterial.where('name LIKE ? OR hiragana LIKE ?', "%#{params[:q]}%", "%#{params[:q]}%")
    respond_to do |format|
      format.json { render json: @rawmaterials }
    end
  end

  def search_unit
    @unit = Rawmaterial.find_by(id: params[:rm_id])&.unit
    respond_to do |format|
      format.json { render json: @unit }
    end
  end

  def search_foodcategory
    foodcategory_id = Rawmaterial.find_by(id: params[:rm_id]).foodcategory_id
    respond_to do |format|
      format.json { render json: foodcategory_id }
    end
  end

  private

  def set_foodstuff
    @foodstuff = Foodstuff.find(params[:id])
  end

  def foodstuff_params
    params.require(:foodstuff).permit(:id, :quantity, :cuisine_id, :rawmaterial_id, :row_order_position)
  end
end

app/controllers/managers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Managers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/managers/passwords_controller.rb
# frozen_string_literal: true

class Managers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/managers/procedures_controller.rb
# frozen_string_literal: true

class Managers::ProceduresController < ApplicationController
  before_action :authenticate_manager!
  before_action :set_procedure, only: %i[edit update destroy]
  layout 'manager'

  def new
    @procedure = Procedure.new
    set_cuisine_and_registerd_pds
  end

  def edit
    set_cuisine_and_registerd_pds
  end

  def create
    @procedure = Procedure.new(procedure_params)
    if @procedure.save
      redirect_to new_managers_procedure_path(cuisine_id: @procedure.cuisine_id), flash: { notice: '手順が追加されました' }
    else
      params[:cuisine_id] = @procedure.cuisine_id
      set_cuisine_and_registerd_pds
      render 'new'
    end
  end

  def update
    if @procedure.update(procedure_params)
      redirect_to new_managers_procedure_path(cuisine_id: @procedure.cuisine_id), flash: { notice: '更新されました' }
    else
      set_cuisine_and_registerd_pds
      render 'edit'
    end
  end

  def destroy
    @procedure.destroy
    case params[:action_name]
    when 'new', 'edit'
      redirect_to new_managers_procedure_path(cuisine_id: @procedure.cuisine_id), flash: { notice: '削除しました' }
    when 'show'
      redirect_to managers_cuisine_path(@procedure.cuisine_id), flash: { notice: '手順を削除しました' }
    end
  end

  def sort
    @procedure = Procedure.find(params[:id])
    @procedure.update(procedure_params)
    head :ok
  end

  private

  def set_procedure
    @procedure = Procedure.find(params[:id])
  end

  def set_cuisine_and_registerd_pds
    @cuisine = Cuisine.find(params[:cuisine_id])
    @registered_procedures = Procedure.where(cuisine_id: params[:cuisine_id]).rank(:row_order)
  end

  def procedure_params
    params.require(:procedure).permit(:cooking_detail, :cuisine_id, :row_order_position)
  end
end

app/controllers/managers/rawmaterials_controller.rb
# frozen_string_literal: true

class Managers::RawmaterialsController < ApplicationController
  before_action :authenticate_manager!
  before_action :set_rawmaterial, only: %i[edit update destroy]
  layout 'manager'
  KAMINARI_PAGINATION_COUNT = 13

  def index
    @q = Rawmaterial.includes(:foodcategory).ransack(params[:q])
    @rawmaterials = @q.result.page(params[:page]).per(KAMINARI_PAGINATION_COUNT)
  end

  def new
    @rawmaterial = Rawmaterial.new
  end

  def edit; end

  def create
    @rawmaterial = Rawmaterial.new(rawmaterial_params)
    if @rawmaterial.save
      redirect_to managers_rawmaterials_path, flash: { notice: "食材区分 #{@rawmaterial.name} が作成されました" }
    else
      render 'new'
    end
  end

  def update
    if @rawmaterial.update(rawmaterial_params)
      redirect_to managers_rawmaterials_path, flash: { notice: '変更されました' }
    else
      render 'edit'
    end
  end

  def destroy
    @rawmaterial&.destroy
    redirect_to managers_rawmaterials_path, flash: { notice: "原材料 #{@rawmaterial.name} が削除されました" }
  end

  private

  def set_rawmaterial
    @rawmaterial = Rawmaterial.find(params[:id])
  end

  def rawmaterial_params
    params.require(:rawmaterial).permit(:name, :hiragana, :unit_id, :foodcategory_id, :expiry_period, :user_id)
  end
end

app/controllers/managers/registrations_controller.rb
# frozen_string_literal: true

class Managers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  layout 'manager'
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/managers/sessions_controller.rb
# frozen_string_literal: true

class Managers::SessionsController < Devise::SessionsController
  layout 'manager_sign_in'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(_resource)
    managers_dashboard_path
  end

  def after_sign_out_path_for(_resource)
    new_manager_session_path
  end

  def login_as_guest_manager
    guest_manager = Manager.create_account_as_guest
    sign_in guest_manager
    redirect_to managers_dashboard_path, notice: "#{guest_manager.name}としてログインしました"
  end
end

app/helpers/managers/cuisines_helper.rb
# frozen_string_literal: true

module Managers::CuisinesHelper
  def disp_cookedstate_name(instance)
    instance.cookedstate.name.to_s if instance.cookedstate_id.present?
  end
end

app/helpers/managers/foodcategories_helper.rb
# frozen_string_literal: true

module Managers::FoodcategoriesHelper
end

app/helpers/managers/foodstuffs_helper.rb
# frozen_string_literal: true

module Managers::FoodstuffsHelper
  def disp_cookedstate_name(instance)
    instance.cookedstate.name.to_s if instance.cookedstate_id.present?
  end
end

app/helpers/managers/procedures_helper.rb
# frozen_string_literal: true

module Managers::ProceduresHelper
end

app/helpers/managers/rawmaterials_helper.rb
# frozen_string_literal: true

module Managers::RawmaterialsHelper
end

app/helpers/managers/tops_helper.rb
# frozen_string_literal: true

module Managers::TopsHelper
end

app/views/managers/shared/_back_to_home.html.erb
<div class="text-center my-2 border border-secondary">
  <p><%= link_to 'トップページへ', root_path, class: 'btn btn-secondary' %></p>
</div>

app/views/managers/shared/_footer.html.erb
  <footer class="main-footer">
    <div class="float-right d-none d-sm-inline">
      Anything you want
    </div>
    <strong>
      Copyright &copy; 2021- <%= link_to @app_name, managers_dashboard_path %>.
    </strong> All rights reserved.
  </footer>

app/views/managers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <div class="text-center my-2">
    <%= link_to 'ログイン画面へ', new_manager_session_path %>
  </div>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <div class="text-center my-2">
    <%= link_to '新しいアカウントを作成', new_manager_registration_path %>
  </div>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to 'Forgot your password?', new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <div class="text-center my-2">
      <%= link_to '確認メールが届きませんでしたか?', new_manager_confirmation_path(resource_name) %>
  </div>
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <div class="text-center my-2">
    <%= link_to 'ロック解除の手順を受け取っていませんか？', new_unlock_path(resource_name) %>
  </div>
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/managers/shared/_manager_footer.html.erb
<footer class="page-footer font-small bg-secondary">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->

</footer>

app/views/managers/shared/_manager_log_out.html.erb
<% if manager_signed_in? %>

<div class="text-center my-2">
  管理者(email):<br />
  <strong><%= current_manager.email %></strong>
</div>

<% unless current_manager.id == 1 %>
<div class="text-center my-2">
  <p><%= link_to 'プロフィール変更(管理者)', edit_manager_registration_path, class: 'btn btn-secondary' %></p>
</div>
<% end %>

<div class="text-center my-2">
  <%# gem devise の　link_toをクリックすると
        - ログアウトできない
        - No route matches [DELETE] "/managers/sign_out"
          - http://localhost:3000/rails/info/routes にアクセスすると
            - destroy_manager_session_path　は存在する
        - 以前変更した %>
  <%= link_to 'ログアウト(管理者)', destroy_manager_session_path, method: :delete, class: 'btn btn-secondary' %>
</div>
<% end %>

app/views/managers/shared/_manager_login.html.erb
<div class="text-center my-2">
  <%= link_to 'ログイン画面へ', new_manager_session_path %>
</div>

app/views/managers/shared/_manager_navbar.html.erb
<nav class="navbar navbar-light bg-secondary">
  <div class="col text-center">
    <a class="navbar-brand" href="#"><%= @app_name %>(管理者)</a>
  </div>
</nav>

app/views/managers/shared/_manager_new_registration.html.erb
  <div class="text-center my-2">
    <%= link_to '新しいアカウントを作成', new_manager_registration_path %>
  </div>

app/views/managers/shared/_sidebar.html.erb
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <%= link_to managers_dashboard_path, class: 'brand-link text-center' do %>
    <span class="brand-text font-weight-light"><%= @app_name %> 管理者画面</span>
  <% end %>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
      </div>
      <div class="info">
        <%# <a href="#" class="d-block">ユーザー名を入れる</a> %>
        <div class="text-white">
        <%= current_manager.name %>
        </div>
      </div>
    </div>

    <!-- SidebarSearch Form -->
    <div class="form-inline">
      <div class="input-group" data-widget="sidebar-search">
        <input class="form-control form-control-sidebar" autocomplete="off" type="search" placeholder="Search" aria-label="Search" />
        <div class="input-group-append">
          <button class="btn btn-sidebar">
            <i class="fas fa-search fa-fw"></i>
          </button>
        </div>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
          <%= link_to managers_dashboard_path, class: add_class_nav_link(@current_page, 'managers/tops#dashboard') do %>
          <p>Home</p>
          <% end %>
        </li>
        <!-- Add icons to the links using the .nav-icon class
              with font-awesome or any other icon font library -->
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-database"></i>
            <p>
              データ一覧
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <%= link_to managers_cuisines_path, class: add_class_nav_link(@current_page, 'foodcategories#index').to_s do %>
                <i class="far fa-circle nav-icon"></i>
                <p>料理レシピ(Done!!)</p>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to managers_foodcategories_path, class: add_class_nav_link(@current_page, 'foodcategories#index').to_s do %>
                <i class="far fa-circle nav-icon"></i>
                <p>食材区分(Done!!)</p>
                <% end %>
            </li>
            <li class="nav-item">
              <%= link_to managers_rawmaterials_path, class: add_class_nav_link(@current_page, 'managers/rawmaterials#index').to_s do %>
                <i class="far fa-circle nav-icon"></i>
                <p>原材料(Done!!)</p>
              <% end %>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>ユーザー(User)</p>
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <p>
            <%= link_to 'ログアウト', destroy_manager_session_path, method: :delete, class: 'nav-link' %>
          </p>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>